//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageBroker.Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPublisher")]
    public interface IPublisher {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPublisher/Publish")]
        void Publish(MessageBroker.Common.Entities.Message message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPublisher/Publish")]
        System.Threading.Tasks.Task PublishAsync(MessageBroker.Common.Entities.Message message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublisherChannel : MessageBroker.Client.ServiceReference1.IPublisher, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublisherClient : System.ServiceModel.ClientBase<MessageBroker.Client.ServiceReference1.IPublisher>, MessageBroker.Client.ServiceReference1.IPublisher {
        
        public PublisherClient() {
        }
        
        public PublisherClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublisherClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublisherClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublisherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Publish(MessageBroker.Common.Entities.Message message) {
            base.Channel.Publish(message);
        }
        
        public System.Threading.Tasks.Task PublishAsync(MessageBroker.Common.Entities.Message message) {
            return base.Channel.PublishAsync(message);
        }
    }
}
