//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageBroker.Client.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.ITopic")]
    public interface ITopic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/GetTopicByName", ReplyAction="http://tempuri.org/ITopic/GetTopicByNameResponse")]
        MessageBroker.Common.Entities.Topic GetTopicByName(string topicName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/GetTopicByName", ReplyAction="http://tempuri.org/ITopic/GetTopicByNameResponse")]
        System.Threading.Tasks.Task<MessageBroker.Common.Entities.Topic> GetTopicByNameAsync(string topicName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/GetExistingTopics", ReplyAction="http://tempuri.org/ITopic/GetExistingTopicsResponse")]
        MessageBroker.Common.Entities.Topic[] GetExistingTopics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/GetExistingTopics", ReplyAction="http://tempuri.org/ITopic/GetExistingTopicsResponse")]
        System.Threading.Tasks.Task<MessageBroker.Common.Entities.Topic[]> GetExistingTopicsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/Add", ReplyAction="http://tempuri.org/ITopic/AddResponse")]
        MessageBroker.Common.Models.BaseResponse Add(MessageBroker.Common.Entities.Topic topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/Add", ReplyAction="http://tempuri.org/ITopic/AddResponse")]
        System.Threading.Tasks.Task<MessageBroker.Common.Models.BaseResponse> AddAsync(MessageBroker.Common.Entities.Topic topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/DeleteByName", ReplyAction="http://tempuri.org/ITopic/DeleteByNameResponse")]
        MessageBroker.Common.Models.BaseResponse DeleteByName(string topicName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/DeleteByName", ReplyAction="http://tempuri.org/ITopic/DeleteByNameResponse")]
        System.Threading.Tasks.Task<MessageBroker.Common.Models.BaseResponse> DeleteByNameAsync(string topicName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITopicChannel : MessageBroker.Client.ServiceReference3.ITopic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TopicClient : System.ServiceModel.ClientBase<MessageBroker.Client.ServiceReference3.ITopic>, MessageBroker.Client.ServiceReference3.ITopic {
        
        public TopicClient() {
        }
        
        public TopicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TopicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MessageBroker.Common.Entities.Topic GetTopicByName(string topicName) {
            return base.Channel.GetTopicByName(topicName);
        }
        
        public System.Threading.Tasks.Task<MessageBroker.Common.Entities.Topic> GetTopicByNameAsync(string topicName) {
            return base.Channel.GetTopicByNameAsync(topicName);
        }
        
        public MessageBroker.Common.Entities.Topic[] GetExistingTopics() {
            return base.Channel.GetExistingTopics();
        }
        
        public System.Threading.Tasks.Task<MessageBroker.Common.Entities.Topic[]> GetExistingTopicsAsync() {
            return base.Channel.GetExistingTopicsAsync();
        }
        
        public MessageBroker.Common.Models.BaseResponse Add(MessageBroker.Common.Entities.Topic topic) {
            return base.Channel.Add(topic);
        }
        
        public System.Threading.Tasks.Task<MessageBroker.Common.Models.BaseResponse> AddAsync(MessageBroker.Common.Entities.Topic topic) {
            return base.Channel.AddAsync(topic);
        }
        
        public MessageBroker.Common.Models.BaseResponse DeleteByName(string topicName) {
            return base.Channel.DeleteByName(topicName);
        }
        
        public System.Threading.Tasks.Task<MessageBroker.Common.Models.BaseResponse> DeleteByNameAsync(string topicName) {
            return base.Channel.DeleteByNameAsync(topicName);
        }
    }
}
