//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageBroker.Common.Entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subscriber", Namespace="http://schemas.datacontract.org/2004/07/MessageBroker.Common.Entities")]
    public partial class Subscriber : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
}
namespace MessageBroker.Common.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionResponse", Namespace="http://schemas.datacontract.org/2004/07/MessageBroker.Common.Models")]
    public partial class SubscriptionResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string QueuePathField;
        
        private string TopicField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueuePath
        {
            get
            {
                return this.QueuePathField;
            }
            set
            {
                this.QueuePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic
        {
            get
            {
                return this.TopicField;
            }
            set
            {
                this.TopicField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISubscriber")]
public interface ISubscriber
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriber/Subscribe", ReplyAction="http://tempuri.org/ISubscriber/SubscribeResponse")]
    MessageBroker.Common.Models.SubscriptionResponse Subscribe(MessageBroker.Common.Entities.Subscriber subscriber, string topic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriber/Subscribe", ReplyAction="http://tempuri.org/ISubscriber/SubscribeResponse")]
    System.Threading.Tasks.Task<MessageBroker.Common.Models.SubscriptionResponse> SubscribeAsync(MessageBroker.Common.Entities.Subscriber subscriber, string topic);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISubscriberChannel : ISubscriber, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SubscriberClient : System.ServiceModel.ClientBase<ISubscriber>, ISubscriber
{
    
    public SubscriberClient()
    {
    }
    
    public SubscriberClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SubscriberClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SubscriberClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SubscriberClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public MessageBroker.Common.Models.SubscriptionResponse Subscribe(MessageBroker.Common.Entities.Subscriber subscriber, string topic)
    {
        return base.Channel.Subscribe(subscriber, topic);
    }
    
    public System.Threading.Tasks.Task<MessageBroker.Common.Models.SubscriptionResponse> SubscribeAsync(MessageBroker.Common.Entities.Subscriber subscriber, string topic)
    {
        return base.Channel.SubscribeAsync(subscriber, topic);
    }
}
