//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageBroker.Common.Entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IAuditableEntity", Namespace="http://schemas.datacontract.org/2004/07/MessageBroker.Common.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MessageBroker.Common.Entities.BaseEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MessageBroker.Common.Entities.Topic))]
    public partial class IAuditableEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CreatedAtField;
        
        private System.DateTime UpdatedAtField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/MessageBroker.Common.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MessageBroker.Common.Entities.Topic))]
    public partial class BaseEntity : MessageBroker.Common.Entities.IAuditableEntity
    {
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Topic", Namespace="http://schemas.datacontract.org/2004/07/MessageBroker.Common.Entities")]
    public partial class Topic : MessageBroker.Common.Entities.BaseEntity
    {
        
        private System.Collections.Generic.List<string> DescriptionsField;
        
        private System.Tuple<int, string> MetadataField;
        
        private string NameField;
        
        private System.Collections.Generic.ICollection<string> QueuePathsField;
        
        private System.Collections.Generic.Dictionary<string, string> TagsField;
        
        private MessageBroker.Common.Enums.TopicType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Descriptions
        {
            get
            {
                return this.DescriptionsField;
            }
            set
            {
                this.DescriptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Tuple<int, string> Metadata
        {
            get
            {
                return this.MetadataField;
            }
            set
            {
                this.MetadataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.ICollection<string> QueuePaths
        {
            get
            {
                return this.QueuePathsField;
            }
            set
            {
                this.QueuePathsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MessageBroker.Common.Enums.TopicType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
}
namespace MessageBroker.Common.Enums
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopicType", Namespace="http://schemas.datacontract.org/2004/07/MessageBroker.Common.Enums")]
    public enum TopicType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Commercial = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Technology = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Business = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://schemas.datacontract.org/2004/07/MessageBroker.Common.Enums")]
    public enum StatusCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 2,
    }
}
namespace MessageBroker.Common.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/MessageBroker.Common.Models")]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private MessageBroker.Common.Enums.StatusCode StatusCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MessageBroker.Common.Enums.StatusCode StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITopic")]
public interface ITopic
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/GetTopicByName", ReplyAction="http://tempuri.org/ITopic/GetTopicByNameResponse")]
    MessageBroker.Common.Entities.Topic GetTopicByName(string topicName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/GetTopicByName", ReplyAction="http://tempuri.org/ITopic/GetTopicByNameResponse")]
    System.Threading.Tasks.Task<MessageBroker.Common.Entities.Topic> GetTopicByNameAsync(string topicName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/GetExistingTopics", ReplyAction="http://tempuri.org/ITopic/GetExistingTopicsResponse")]
    MessageBroker.Common.Entities.Topic[] GetExistingTopics();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/GetExistingTopics", ReplyAction="http://tempuri.org/ITopic/GetExistingTopicsResponse")]
    System.Threading.Tasks.Task<MessageBroker.Common.Entities.Topic[]> GetExistingTopicsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/Add", ReplyAction="http://tempuri.org/ITopic/AddResponse")]
    MessageBroker.Common.Models.BaseResponse Add(MessageBroker.Common.Entities.Topic topic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/Add", ReplyAction="http://tempuri.org/ITopic/AddResponse")]
    System.Threading.Tasks.Task<MessageBroker.Common.Models.BaseResponse> AddAsync(MessageBroker.Common.Entities.Topic topic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/DeleteByName", ReplyAction="http://tempuri.org/ITopic/DeleteByNameResponse")]
    MessageBroker.Common.Models.BaseResponse DeleteByName(string topicName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopic/DeleteByName", ReplyAction="http://tempuri.org/ITopic/DeleteByNameResponse")]
    System.Threading.Tasks.Task<MessageBroker.Common.Models.BaseResponse> DeleteByNameAsync(string topicName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITopicChannel : ITopic, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TopicClient : System.ServiceModel.ClientBase<ITopic>, ITopic
{
    
    public TopicClient()
    {
    }
    
    public TopicClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TopicClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TopicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TopicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public MessageBroker.Common.Entities.Topic GetTopicByName(string topicName)
    {
        return base.Channel.GetTopicByName(topicName);
    }
    
    public System.Threading.Tasks.Task<MessageBroker.Common.Entities.Topic> GetTopicByNameAsync(string topicName)
    {
        return base.Channel.GetTopicByNameAsync(topicName);
    }
    
    public MessageBroker.Common.Entities.Topic[] GetExistingTopics()
    {
        return base.Channel.GetExistingTopics();
    }
    
    public System.Threading.Tasks.Task<MessageBroker.Common.Entities.Topic[]> GetExistingTopicsAsync()
    {
        return base.Channel.GetExistingTopicsAsync();
    }
    
    public MessageBroker.Common.Models.BaseResponse Add(MessageBroker.Common.Entities.Topic topic)
    {
        return base.Channel.Add(topic);
    }
    
    public System.Threading.Tasks.Task<MessageBroker.Common.Models.BaseResponse> AddAsync(MessageBroker.Common.Entities.Topic topic)
    {
        return base.Channel.AddAsync(topic);
    }
    
    public MessageBroker.Common.Models.BaseResponse DeleteByName(string topicName)
    {
        return base.Channel.DeleteByName(topicName);
    }
    
    public System.Threading.Tasks.Task<MessageBroker.Common.Models.BaseResponse> DeleteByNameAsync(string topicName)
    {
        return base.Channel.DeleteByNameAsync(topicName);
    }
}
