//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageBroker.Client.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ISubscriber")]
    public interface ISubscriber {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriber/Subscribe", ReplyAction="http://tempuri.org/ISubscriber/SubscribeResponse")]
        MessageBroker.Common.Models.SubscriptionResponse Subscribe(MessageBroker.Common.Entities.Subscriber subscriber, string topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriber/Subscribe", ReplyAction="http://tempuri.org/ISubscriber/SubscribeResponse")]
        System.Threading.Tasks.Task<MessageBroker.Common.Models.SubscriptionResponse> SubscribeAsync(MessageBroker.Common.Entities.Subscriber subscriber, string topic);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubscriberChannel : MessageBroker.Client.ServiceReference2.ISubscriber, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscriberClient : System.ServiceModel.ClientBase<MessageBroker.Client.ServiceReference2.ISubscriber>, MessageBroker.Client.ServiceReference2.ISubscriber {
        
        public SubscriberClient() {
        }
        
        public SubscriberClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubscriberClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriberClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriberClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MessageBroker.Common.Models.SubscriptionResponse Subscribe(MessageBroker.Common.Entities.Subscriber subscriber, string topic) {
            return base.Channel.Subscribe(subscriber, topic);
        }
        
        public System.Threading.Tasks.Task<MessageBroker.Common.Models.SubscriptionResponse> SubscribeAsync(MessageBroker.Common.Entities.Subscriber subscriber, string topic) {
            return base.Channel.SubscribeAsync(subscriber, topic);
        }
    }
}
